### ISSUE TITLE
Frontend: Register Page

### ISSUE THREAD

**Issue by IkennaOnuorah** [Wellforce/WellForce#8]
# User story section
As a user I want to be able to register for a WellForce account entering all required information like First name, Last Name, Email, Password, and Confirm Password.
# Description
Create required fields for registration so user can input information
# Acceptance Criteria

- [ ] Register component should be created
- [ ] First Name input field is implemented
- [ ] Last Name input field is implemented
- [ ] Email (required) input field is implemented
- [ ] Password input field is implemented 
- [ ] Confirm Password input field is implemented
- [ ] Register button takes the user to Login page

# Definition of Done

- [ ] All A/C are satisfied
- [ ] Register UI meets all required fields
