### ISSUE TITLE
Frontend: Login Page

### ISSUE THREAD

**Issue by IkennaOnuorah** [Wellforce/WellForce#9]
# User story section
As a user I want to be able to login into my account with a username and password.
# Description
Creates email and password field for user to input information
# Acceptance Criteria

- [ ] Login component should be created
- [ ] Email input field is implemented
- [ ] Password input field is implemented 
- [ ] Login button takes the user to Activities page

# Definition of Done

- [ ] All A/C are satisfied
- [ ] Login UI meets all required fields
